name: CI for To-Do List App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install HTMLHint
        run: npm install -g htmlhint

      - name: Lint HTML
        run: htmlhint index.html

      - name: Install Stylelint
        run: npm install -g stylelint stylelint-config-standard

      - name: Lint CSS
        run: stylelint "CSS/*.css"

      - name: Install ESLint
        run: npm install -g eslint

      - name: Lint JavaScript
        run: eslint "JS/*.js"
